# Generated by Django 2.2.5 on 2020-11-16 13:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
