# Generated by Django 4.2.1 on 2023-05-17 09:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_contactinformation_customer_news_newscategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('key_word', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.productcategory'),
            preserve_default=False,
        ),
    ]
