# Generated by Django 4.2.1 on 2023-05-18 06:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_content',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
    ]
