# Generated by Django 4.2.1 on 2023-05-18 06:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_news_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
