# Generated by Django 4.2.1 on 2023-05-18 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='sub_product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.productcategory'),
        ),
    ]
