# Generated by Django 4.2.1 on 2023-05-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_productcategory_sub_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='sub_product_category',
            new_name='parent_product_category',
        ),
    ]
