# Generated by Django 4.2.1 on 2023-05-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_rename_sub_product_category_productcategory_parent_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_parent_category',
            field=models.BooleanField(default=False),
        ),
    ]
