# Generated by Django 4.2.1 on 2023-05-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ManyToManyField(to='apps.imageelement'),
        ),
    ]
