# Generated by Django 4.2.1 on 2023-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_imageelement_rename_image_products_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='apps.imageelement'),
        ),
    ]
