# Generated by Django 4.2.1 on 2023-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_alter_products_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='image',
            field=models.FileField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
