# Generated by Django 4.2.1 on 2023-05-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_alter_productreviews_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='user_id',
            new_name='user',
        ),
    ]
