# Generated by Django 4.2.1 on 2023-05-20 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0025_rename_user_id_productreviews_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='short_name',
        ),
        migrations.AddField(
            model_name='newscategory',
            name='unique_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='productreviews',
            unique_together={('user_id', 'product')},
        ),
    ]
