# Generated by Django 4.2.1 on 2023-05-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_rename_user_productreviews_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='unique_name',
            field=models.CharField(max_length=255),
        ),
    ]
