# Generated by Django 4.2.1 on 2023-06-01 12:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_getintouch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unique_name', models.CharField(max_length=255)),
                ('key_word', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=8)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.FileField(upload_to='uploads/% Y/% m/% d/')),
                ('employee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employeeposition')),
            ],
        ),
    ]
