# Generated by Django 4.2.1 on 2023-06-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_alter_employeeprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='picture',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='imageelement',
            name='image',
            field=models.FileField(upload_to='uploads/Y/m/d/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Y/m/d/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='uploads/Y/m/d/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Y/m/d/'),
        ),
    ]
