# Generated by Django 4.2.1 on 2023-06-22 11:04

import ckeditor_uploader.fields
from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_voucher_alter_employeeprofile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
