# Generated by Django 4.2.1 on 2023-06-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='instagram',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tiktok',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='whatsapp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
